// sample.data
const products = [
  // 📁 전자기기 (8개)
  {
    productCode: "E001",
    productName: "27인치 모니터",
    category: "전자기기",
    stockQty: 25,
    supplier: "뷰텍코리아",
    purchasePrice: 190000,
    rating: 4.6,
  },
  {
    productCode: "E001",
    productName: "27인치 모니터",
    category: "전자기기",
    stockQty: 25,
    supplier: "뷰텍코리아",
    purchasePrice: 190000,
    rating: 4.6,
  },
  {
    productCode: "E002",
    productName: "스마트 TV 43인치",
    category: "전자기기",
    stockQty: 12,
    supplier: "삼성전자",
    purchasePrice: 420000,
    rating: 4.8,
  },
  {
    productCode: "E003",
    productName: "프로젝터",
    category: "전자기기",
    stockQty: 8,
    supplier: "LG전자",
    purchasePrice: 380000,
    rating: 4.5,
  },
  {
    productCode: "E004",
    productName: "데스크탑 본체",
    category: "전자기기",
    stockQty: 10,
    supplier: "한빛IT",
    purchasePrice: 750000,
    rating: 4.7,
  },
  {
    productCode: "E005",
    productName: "노트북 15인치",
    category: "전자기기",
    stockQty: 18,
    supplier: "탑컴퓨터",
    purchasePrice: 640000,
    rating: 4.4,
  },
  {
    productCode: "E006",
    productName: "미니빔 프로젝터",
    category: "전자기기",
    stockQty: 15,
    supplier: "뷰텍코리아",
    purchasePrice: 290000,
    rating: 4.3,
  },
  {
    productCode: "E007",
    productName: "데스크탑 모니터암",
    category: "전자기기",
    stockQty: 30,
    supplier: "오피스테크",
    purchasePrice: 58000,
    rating: 4.1,
  },
  {
    productCode: "E008",
    productName: "게이밍 모니터 32인치",
    category: "전자기기",
    stockQty: 9,
    supplier: "뷰텍코리아",
    purchasePrice: 330000,
    rating: 4.9,
  },

  // 🖱 주변기기 (8개)
  {
    productCode: "P001",
    productName: "무선 마우스",
    category: "주변기기",
    stockQty: 120,
    supplier: "ABC전자",
    purchasePrice: 18000,
    rating: 4.5,
  },
  {
    productCode: "P002",
    productName: "기계식 키보드",
    category: "주변기기",
    stockQty: 35,
    supplier: "한빛IT",
    purchasePrice: 55000,
    rating: 4.6,
  },
  {
    productCode: "P003",
    productName: "마우스패드 대형",
    category: "주변기기",
    stockQty: 85,
    supplier: "오피스존",
    purchasePrice: 9000,
    rating: 4.2,
  },
  {
    productCode: "P004",
    productName: "USB 메모리 64GB",
    category: "주변기기",
    stockQty: 200,
    supplier: "메모리월드",
    purchasePrice: 12000,
    rating: 4.4,
  },
  {
    productCode: "P005",
    productName: "무선 키보드 세트",
    category: "주변기기",
    stockQty: 60,
    supplier: "ABC전자",
    purchasePrice: 35000,
    rating: 4.3,
  },
  {
    productCode: "P006",
    productName: "USB-C 허브 6in1",
    category: "주변기기",
    stockQty: 25,
    supplier: "디지털파트",
    purchasePrice: 32000,
    rating: 4.7,
  },
  {
    productCode: "P007",
    productName: "HDMI 케이블 2m",
    category: "주변기기",
    stockQty: 180,
    supplier: "케이블마트",
    purchasePrice: 3500,
    rating: 4.1,
  },
  {
    productCode: "P008",
    productName: "외장하드 1TB",
    category: "주변기기",
    stockQty: 42,
    supplier: "디지털파트",
    purchasePrice: 62000,
    rating: 4.6,
  },

  // 🗂 사무용품 (8개)
  {
    productCode: "O001",
    productName: "노트북 거치대",
    category: "사무용품",
    stockQty: 25,
    supplier: "탑오피스",
    purchasePrice: 22000,
    rating: 4.4,
  },
  {
    productCode: "O002",
    productName: "책상용 LED 스탠드",
    category: "사무용품",
    stockQty: 18,
    supplier: "라이트하우스",
    purchasePrice: 27000,
    rating: 4.5,
  },
  {
    productCode: "O003",
    productName: "사무용 의자",
    category: "사무용품",
    stockQty: 10,
    supplier: "오피스테크",
    purchasePrice: 125000,
    rating: 4.6,
  },
  {
    productCode: "O004",
    productName: "A4 복사용지 80g",
    category: "사무용품",
    stockQty: 500,
    supplier: "페이퍼랜드",
    purchasePrice: 4800,
    rating: 4.3,
  },
  {
    productCode: "O005",
    productName: "화이트보드 마카 세트",
    category: "사무용품",
    stockQty: 70,
    supplier: "탑오피스",
    purchasePrice: 6500,
    rating: 4.2,
  },
  {
    productCode: "O006",
    productName: "문서보관 박스",
    category: "사무용품",
    stockQty: 45,
    supplier: "오피스존",
    purchasePrice: 8500,
    rating: 4.1,
  },
  {
    productCode: "O007",
    productName: "파일 바인더 3단",
    category: "사무용품",
    stockQty: 120,
    supplier: "페이퍼랜드",
    purchasePrice: 3200,
    rating: 4.0,
  },
  {
    productCode: "O008",
    productName: "책상 정리 트레이",
    category: "사무용품",
    stockQty: 65,
    supplier: "탑오피스",
    purchasePrice: 9800,
    rating: 4.3,
  },

  // 📱 모바일기기 (8개)
  {
    productCode: "M001",
    productName: "휴대용 보조배터리 20000mAh",
    category: "모바일기기",
    stockQty: 45,
    supplier: "모바일코리아",
    purchasePrice: 27000,
    rating: 4.6,
  },
  {
    productCode: "M002",
    productName: "무선 충전 패드",
    category: "모바일기기",
    stockQty: 70,
    supplier: "모바일코리아",
    purchasePrice: 18000,
    rating: 4.5,
  },
  {
    productCode: "M003",
    productName: "스마트폰 거치대",
    category: "모바일기기",
    stockQty: 95,
    supplier: "디지털파트",
    purchasePrice: 7500,
    rating: 4.3,
  },
  {
    productCode: "M004",
    productName: "충전 케이블 1m",
    category: "모바일기기",
    stockQty: 250,
    supplier: "케이블마트",
    purchasePrice: 3500,
    rating: 4.4,
  },
  {
    productCode: "M005",
    productName: "무선 이어폰",
    category: "모바일기기",
    stockQty: 35,
    supplier: "ABC전자",
    purchasePrice: 89000,
    rating: 4.7,
  },
  {
    productCode: "M006",
    productName: "스마트워치",
    category: "모바일기기",
    stockQty: 22,
    supplier: "모바일코리아",
    purchasePrice: 158000,
    rating: 4.6,
  },
  {
    productCode: "M007",
    productName: "스마트폰 케이스",
    category: "모바일기기",
    stockQty: 140,
    supplier: "디지털파트",
    purchasePrice: 6500,
    rating: 4.2,
  },
  {
    productCode: "M008",
    productName: "스마트워치 충전 케이블",
    category: "모바일기기",
    stockQty: 55,
    supplier: "모바일코리아",
    purchasePrice: 9800,
    rating: 4.3,
  },

  // 🎧 음향기기 (9개)
  {
    productCode: "A001",
    productName: "게이밍 헤드셋",
    category: "음향기기",
    stockQty: 15,
    supplier: "사운드맥스",
    purchasePrice: 68000,
    rating: 4.7,
  },
  {
    productCode: "A002",
    productName: "블루투스 스피커",
    category: "음향기기",
    stockQty: 25,
    supplier: "사운드맥스",
    purchasePrice: 59000,
    rating: 4.6,
  },
  {
    productCode: "A003",
    productName: "유선 이어폰",
    category: "음향기기",
    stockQty: 100,
    supplier: "모바일코리아",
    purchasePrice: 12000,
    rating: 4.2,
  },
  {
    productCode: "A004",
    productName: "헤드폰 거치대",
    category: "음향기기",
    stockQty: 50,
    supplier: "오피스테크",
    purchasePrice: 15000,
    rating: 4.3,
  },
  {
    productCode: "A005",
    productName: "녹음용 마이크",
    category: "음향기기",
    stockQty: 20,
    supplier: "사운드맥스",
    purchasePrice: 97000,
    rating: 4.8,
  },
  {
    productCode: "A006",
    productName: "스튜디오 스피커",
    category: "음향기기",
    stockQty: 8,
    supplier: "사운드맥스",
    purchasePrice: 230000,
    rating: 4.9,
  },
  {
    productCode: "A007",
    productName: "마이크 케이블",
    category: "음향기기",
    stockQty: 120,
    supplier: "케이블마트",
    purchasePrice: 8000,
    rating: 4.4,
  },
  {
    productCode: "A008",
    productName: "소형 앰프",
    category: "음향기기",
    stockQty: 10,
    supplier: "사운드맥스",
    purchasePrice: 125000,
    rating: 4.7,
  },
  {
    productCode: "A009",
    productName: "콘덴서 마이크",
    category: "음향기기",
    stockQty: 12,
    supplier: "사운드맥스",
    purchasePrice: 145000,
    rating: 4.8,
  },

  // 🎒 액세서리 (9개)
  {
    productCode: "X001",
    productName: "스마트워치 밴드",
    category: "액세서리",
    stockQty: 85,
    supplier: "디지털파트",
    purchasePrice: 9000,
    rating: 4.4,
  },
  {
    productCode: "X002",
    productName: "노트북 파우치",
    category: "액세서리",
    stockQty: 45,
    supplier: "탑오피스",
    purchasePrice: 21000,
    rating: 4.5,
  },
  {
    productCode: "X003",
    productName: "키보드 커버",
    category: "액세서리",
    stockQty: 110,
    supplier: "ABC전자",
    purchasePrice: 5500,
    rating: 4.1,
  },
  {
    productCode: "X004",
    productName: "마우스 보호 케이스",
    category: "액세서리",
    stockQty: 75,
    supplier: "오피스존",
    purchasePrice: 7200,
    rating: 4.3,
  },
  {
    productCode: "X005",
    productName: "USB 케이스",
    category: "액세서리",
    stockQty: 95,
    supplier: "디지털파트",
    purchasePrice: 4800,
    rating: 4.2,
  },
  {
    productCode: "X006",
    productName: "케이블 정리 홀더",
    category: "액세서리",
    stockQty: 150,
    supplier: "케이블마트",
    purchasePrice: 3200,
    rating: 4.4,
  },
  {
    productCode: "X007",
    productName: "휴대폰 링 거치대",
    category: "액세서리",
    stockQty: 135,
    supplier: "모바일코리아",
    purchasePrice: 5500,
    rating: 4.3,
  },
  {
    productCode: "X008",
    productName: "노트북 스티커 세트",
    category: "액세서리",
    stockQty: 60,
    supplier: "탑오피스",
    purchasePrice: 3800,
    rating: 4.1,
  },
  {
    productCode: "X009",
    productName: "무선충전 수신 모듈",
    category: "액세서리",
    stockQty: 25,
    supplier: "디지털파트",
    purchasePrice: 12500,
    rating: 4.5,
  },
];
